name: Release Staging

on:
  push:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          yarn-
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Install semantic-release extra plugins
      run: yarn add @semantic-release/changelog -D
    - name: Lint
      run: yarn lint:ts && yarn lint:sol
    - name: Build
      run: yarn build
    - name: Test
      run: yarn test
    - name: Cache deployments
      id: cache-primes
      uses: actions/cache@v3
      with:
        path: deployments
        key: deployments

    - name: Deploy to staging chain
      run: yarn hardhat deploy --gasPrice 30000000000 --network sokol
      env:
        MNEMONIC: ${{ secrets.MNEMONIC_SOKOL }}
        ETH_NODE_URI_SOKOL: ${{ secrets.ETH_NODE_URI_SOKOL }}
    - name: Verify contracts
      run: yarn hardhat sourcify --network sokol
      env:
        MNEMONIC: ${{ secrets.MNEMONIC_SOKOL }}
        ETH_NODE_URI_SOKOL: ${{ secrets.ETH_NODE_URI_SOKOL }}
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: npx semantic-release
